package RespaldosBD;
import BaseDatos.Funcionalidad;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class CrearRespaldo extends javax.swing.JFrame 
{
    public String usuario;
    public String contraseña;
    public Opciones op;//se va a igualar a la ventana principal, así no se pierde la referencia de la conexión
    List<String> listDirectorios = new ArrayList<String>();
    public Funcionalidad db;
    ResultSet resultado;
    
    
    Runnable run = new Runnable()  //creacion del hilo para la exportacion
    {
        @Override
         public void run(){ 
            Exportar();
         }
    };
    

    //CONSTRUCTOR
    public CrearRespaldo() {
        initComponents(); //Carga los elementos del JFrame o JPanel
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    }
                }
            }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(CrearRespaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        
        this.setLocationRelativeTo(null); //Centa la pantalla
        this.setTitle("Creación de Respaldos"); //Título
        this.setResizable(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadioBut = new javax.swing.JPanel();
        radioFull = new javax.swing.JRadioButton();
        radioSchema = new javax.swing.JRadioButton();
        radioTablas = new javax.swing.JRadioButton();
        boxTablas = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegresar = new javax.swing.JButton();
        lblDirectorios = new javax.swing.JLabel();
        lblDirDirectorio = new javax.swing.JLabel();
        boxDirectorios = new javax.swing.JComboBox();
        txtDirDirectorio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaComando = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        lblTipoElegido = new javax.swing.JLabel();
        lblNombreArchivo = new javax.swing.JLabel();
        txtNombreArchivo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subitem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRadioBut.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Respaldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        radioFull.setText("Full");
        radioFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFullActionPerformed(evt);
            }
        });

        radioSchema.setText("Schema");
        radioSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSchemaActionPerformed(evt);
            }
        });

        radioTablas.setText("Tabla");
        radioTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTablasActionPerformed(evt);
            }
        });

        boxTablas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boxTablas.setEnabled(false);

        javax.swing.GroupLayout panelRadioButLayout = new javax.swing.GroupLayout(panelRadioBut);
        panelRadioBut.setLayout(panelRadioButLayout);
        panelRadioButLayout.setHorizontalGroup(
            panelRadioButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadioButLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(radioTablas)
                .addGap(8, 8, 8)
                .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radioSchema)
                .addGap(33, 33, 33)
                .addComponent(radioFull)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelRadioButLayout.setVerticalGroup(
            panelRadioButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioButLayout.createSequentialGroup()
                .addGroup(panelRadioButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSchema)
                    .addComponent(radioTablas)
                    .addComponent(radioFull)
                    .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar al Menú");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblDirectorios.setText("Directorios");

        lblDirDirectorio.setText("Dirección de Directorio");

        boxDirectorios.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boxDirectorios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxDirectoriosItemStateChanged(evt);
            }
        });

        txtDirDirectorio.setEditable(false);
        txtDirDirectorio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDirDirectorio.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        areaComando.setEditable(false);
        areaComando.setColumns(1);
        areaComando.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaComando.setLineWrap(true);
        areaComando.setRows(5);
        areaComando.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaComando);

        btnCrear.setText("Crear respaldo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblTipoElegido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTipoElegido.setText("...");

        lblNombreArchivo.setText("Nombre del Archivo a Exportar:");

        txtNombreArchivo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblTitulo.setBackground(new java.awt.Color(255, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Creación de Respaldos");
        lblTitulo.setOpaque(true);

        jMenu1.setText("Opciones");

        subitem2.setText("Salir");
        subitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subitem2ActionPerformed(evt);
            }
        });
        jMenu1.add(subitem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelRadioBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(119, 119, 119)
                                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblTipoElegido, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDirDirectorio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDirDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDirectorios)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(boxDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNombreArchivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 68, Short.MAX_VALUE))
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRadioBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirectorios)
                    .addComponent(boxDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreArchivo)
                    .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDirDirectorio))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblTipoElegido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //////////////////////////////////////////////////  ACCIONES  ////////////////////////////////////////////////////////
    
    private void radioFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFullActionPerformed
       boxTablas.enable(false);
       radioTablas.setSelected(false);
       radioSchema.setSelected(false);
    }//GEN-LAST:event_radioFullActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        op.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void boxDirectoriosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxDirectoriosItemStateChanged
        if(listDirectorios.size() > 0 && boxDirectorios.getSelectedIndex() != -1 )
            txtDirDirectorio.setText(listDirectorios.get(boxDirectorios.getSelectedIndex()));
    }//GEN-LAST:event_boxDirectoriosItemStateChanged

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        if(validaciones()){
            String mensaje="Creando respaldo "; //Variable con el mensaje "Creando respaldo "

            if(radioFull.isSelected()) //Si se selecciona la opción Full
                mensaje= mensaje+"Full..."; //El mensaje será "Creando respaldo Full..."
            
            else if (radioSchema.isSelected()) //Si se selecciona la opción Schema
                mensaje= mensaje+"del Schema..."; //El mensaje será "Creando respaldo de Schema..."
            
            else if (radioTablas.isSelected()) //Si se selecciona la opción Tablas
                mensaje= mensaje+"de Tabla..."; //El mensaje será "Creando respaldo de Tablas..."
            
            lblTipoElegido.setText(mensaje); //El label cambia su contenido con el texto
            
            btnCrear.setEnabled(false);//para bloquear el boton de crear
            btnRegresar.setEnabled(false);
            
            Thread h1 = new Thread(run);
            h1.start();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void subitem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subitem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_subitem2ActionPerformed

    private void radioTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTablasActionPerformed
        boxTablas.enable(true);
        radioSchema.setSelected(false);
        radioFull.setSelected(false);
    }//GEN-LAST:event_radioTablasActionPerformed

    private void radioSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSchemaActionPerformed
        boxTablas.enable(false);
        radioTablas.setSelected(false);
        radioFull.setSelected(false);
    }//GEN-LAST:event_radioSchemaActionPerformed

    
    
    //////////////////////////////////////////////////  METODOS  ////////////////////////////////////////////////////////
    
    public void cargarDirectorios()//metodo de cargar directorios
    {
        ResultSet resultado = db.cargarDirectorios();

        boxDirectorios.removeAllItems();
        listDirectorios.clear();

             try {
                 while(resultado.next())
                 {
                         boxDirectorios.addItem(resultado.getString(1));
                         listDirectorios.add(resultado.getString(2));

                 }
                 boxDirectorios.setSelectedIndex(-1);
             } catch (SQLException ex) {
                 Logger.getLogger(CrearRespaldo.class.getName()).log(Level.SEVERE, null, ex);
             }
    }


    public void cargarTablasUsuario()//metodo de cargar directorios
    {
        ResultSet resultado = db.cargarTablasUsuario(usuario);
       

        boxTablas.removeAllItems();
             try {
                 while(resultado.next())
                 {
                         boxTablas.addItem(resultado.getString("TABLE_NAME"));
                         
                 }
                 boxTablas.setSelectedIndex(-1);
                
             } catch (SQLException ex) {
                 Logger.getLogger(CrearRespaldo.class.getName()).log(Level.SEVERE, null, ex);
             }
    }
    
    private void Exportar()//metodo para hacer la exportacion
    {
           String s = null;
           String tipoRespaldo = "";//el tipo de respaldo que se hará
           String dir = "";//directorio donde se guardara el respaldo

           
           if(radioTablas.isSelected()){
                    tipoRespaldo = "TABLES = "+boxTablas.getSelectedItem().toString();
           }
           if(radioSchema.isSelected()){
                tipoRespaldo = "SCHEMAS = "+usuario;
           }
           if(radioFull.isSelected()){
               tipoRespaldo = "FULL=Y";
           }
           
           dir = boxDirectorios.getSelectedItem().toString();

           try {
                String comando;
                comando = "cmd /c " + "EXPDP" + " " + usuario +"/"+ contraseña  + " " + tipoRespaldo +" DIRECTORY = "+ dir 
                        + " DUMPFILE = " + txtNombreArchivo.getText() +".dmp LOGFILE = " + txtNombreArchivo.getText() + "_log.log";

                // Ejcutamos el comando
                Process p = Runtime.getRuntime().exec(comando);

                BufferedReader stdInput = new BufferedReader(new InputStreamReader(
                                p.getInputStream()));

                BufferedReader stdError = new BufferedReader(new InputStreamReader(
                                p.getErrorStream()));

                // Leemos la salida del comando
                while ((s = stdInput.readLine()) != null) 
                {
                    areaComando.append(s + "\n");
                }

                // Leemos los errores si los hubiera
                while ((s = stdError.readLine()) != null)
                {
                    areaComando.append(s + "\n");
                }
                lblTipoElegido.setText("El respaldo ha concluido");
                JOptionPane.showMessageDialog(null," La Exportación ha concluido..","Proceso Completado",JOptionPane.INFORMATION_MESSAGE);
                btnRegresar.setEnabled(true);
            } 
            catch (IOException e) 
            {
                System.out.println("Excepción: ");
                e.printStackTrace();
                System.exit(-1);
            }
    }
    
    public boolean validaciones()
    {
        if(!radioTablas.isSelected() && !radioSchema.isSelected() && !radioFull.isSelected()){
            JOptionPane.showMessageDialog(null,"Debe seleccionar el tipo de respaldo","", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(radioTablas.isSelected() && boxTablas.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar la tabla a respaldar","", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(boxDirectorios.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un directorio","", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(txtNombreArchivo.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe darle un nombre al archivo de respaldo","", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaComando;
    private javax.swing.JComboBox boxDirectorios;
    private javax.swing.JComboBox boxTablas;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDirDirectorio;
    private javax.swing.JLabel lblDirectorios;
    private javax.swing.JLabel lblNombreArchivo;
    private javax.swing.JLabel lblTipoElegido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelRadioBut;
    private javax.swing.JRadioButton radioFull;
    private javax.swing.JRadioButton radioSchema;
    private javax.swing.JRadioButton radioTablas;
    private javax.swing.JMenuItem subitem2;
    private javax.swing.JTextField txtDirDirectorio;
    private javax.swing.JTextField txtNombreArchivo;
    // End of variables declaration//GEN-END:variables
}
