package RespaldosBD;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import BaseDatos.Funcionalidad;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class InicioSesion extends javax.swing.JFrame 
{
    Funcionalidad fun= new Funcionalidad();
    ResultSet resultado;
    String user;
    String pass;
    
    public InicioSesion() 
    {
        initComponents(); //Carda los elementos del JFrame o JPanel
        setLocationRelativeTo(null); //Centa la pantalla
        setResizable(false); //Para que no se minimice ni maximice la ventana
        setTitle("Inicio de Sesión"); //Título
        ImageIcon imagen=new ImageIcon("src/Imagenes/java-logo2.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(lblJava.getWidth(),lblJava.getHeight(),Image.SCALE_DEFAULT));
        lblJava.setIcon(icono);
        //
        ImageIcon imagen2=new ImageIcon("src/Imagenes/OracleDB.gif");
        Icon icono2=new ImageIcon(imagen2.getImage().getScaledInstance(lblOracle.getWidth(),lblOracle.getHeight(),Image.SCALE_DEFAULT));
        lblOracle.setIcon(icono2);
        //
        ImageIcon imagen3=new ImageIcon("src/Imagenes/user.png");
        Icon icono3=new ImageIcon(imagen3.getImage().getScaledInstance(lblUsuario.getWidth(),lblUsuario.getHeight(),Image.SCALE_DEFAULT));
        lblUsuario.setIcon(icono3);
        //
        ImageIcon imagen4=new ImageIcon("src/Imagenes/password.png");
        Icon icono4=new ImageIcon(imagen4.getImage().getScaledInstance(lblContrasena.getWidth(),lblContrasena.getHeight(),Image.SCALE_DEFAULT));
        lblContrasena.setIcon(icono4);
        
        this.getContentPane().setBackground(Color.white);
    }
    
 
    public void cargarUsuarios() /// carga los usuarios en la interfaz
    {
      fun.conectar("system","oracle");
      resultado=fun.usuarios();
      
      if(resultado!=null)
      {
          try 
          {
              comboUsuarios.removeAllItems();
              while(resultado.next())
              {
                  comboUsuarios.addItem(resultado.getString(1));
              }
              comboUsuarios.setSelectedIndex(-1);
              fun.Desconectar();
          } 
          catch(SQLException ex) 
          {
              Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboUsuarios = new javax.swing.JComboBox<>();
        btnInicioSesion = new javax.swing.JButton();
        campoContrasena = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();
        lblJava = new javax.swing.JLabel();
        lblOracle = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subitem1 = new javax.swing.JMenuItem();
        subitem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnInicioSesion.setText("Iniciar Sesión");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(255, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Inicio de Sesión");
        lblTitulo.setOpaque(true);

        lblJava.setBorder(new javax.swing.border.MatteBorder(null));

        lblOracle.setBorder(new javax.swing.border.MatteBorder(null));

        lblUsuario.setBorder(new javax.swing.border.MatteBorder(null));

        lblContrasena.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu1.setText("Opciones");

        subitem1.setText("Equipo Desarrollador");
        subitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subitem1ActionPerformed(evt);
            }
        });
        jMenu1.add(subitem1);

        subitem2.setText("Salir");
        subitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subitem2ActionPerformed(evt);
            }
        });
        jMenu1.add(subitem2);

        barraSuperior.add(jMenu1);

        setJMenuBar(barraSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOracle, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(lblContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOracle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
        user=(String)comboUsuarios.getSelectedItem();
        pass=String.valueOf(campoContrasena.getPassword());
       
        if(fun.conectar(user, pass))
        {
            Opciones opc=new Opciones();
         
            opc.db=this.fun;
            opc.usuario=user;
            opc.contraseña = pass;

            opc.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Ha iniciado exitósamente");
       }
       else
       {
          JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error al iniciar sesión",
                  JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void subitem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subitem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EquipoDesarrollador ed= new EquipoDesarrollador();
        ed.setVisible(true);
    }//GEN-LAST:event_subitem1ActionPerformed

    private void subitem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subitem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_subitem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see htcomboUsuariosoad.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraSuperior;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JPasswordField campoContrasena;
    private javax.swing.JComboBox<String> comboUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblJava;
    private javax.swing.JLabel lblOracle;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem subitem1;
    private javax.swing.JMenuItem subitem2;
    // End of variables declaration//GEN-END:variables
}
